version: "3"

services:
  backend:
    image: usermgt:latest
    build: ./backend
    environment:
    - DB_DRIVER=postgres
    - DB_NAME=usermgt
    - DB_HOST=database
    - DB_PORT=5432
    - DB_USERNAME=svc-usermgt
    - DB_PASSWORD=changeme
    ports:
    - 38080:8080
  database:
    image: postgres:16.3
    environment:
    - POSTGRES_DB=usermgt
    - POSTGRES_PASSWORD=changeme
    - POSTGRES_USER=svc-usermgt
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres-data: